/- SPDX-License-Identifier: Apache-2.0 -/

import SealV2
import Test.V2ValidationFixtures

/-!
# Field-warrant corpus + negative-witness mutation machinery

The SINGLE SOURCE OF TRUTH for the field-warrant fixtures and the
step-executing negative-control corpus. Both `Test/FieldWarrant.lean` (the
human SHOW suite) and `Test/FieldWarrantMutation.lean` (the mechanical
negative-witness harness) import this module, so there is one corpus, not two
that can drift.

## The negative witness (council requirement, 2026-07-23 01:56)

A hand tamper matrix proves a control CAN be broken. The stronger MECHANICAL
form is a *negative witness*: for a control that CLAIMS to measure reason R,
construct a mutant that removes R's discriminator and require the control's
outcome to CHANGE (the control "goes red for the asserted reason"). The
frisk-F1 defect class — a control whose Block is provided by its own gate, so
it stays green even when signature binding is removed — is caught mechanically
by exactly this: such a control is INSENSITIVE to the signature mutant and
SENSITIVE to its own gate mutant, the inverse of an honest signature control.

Two mutant families, both computed at RUNTIME (no per-mutant recompile):

* `M_sig` — `verifyNoSig`: verification with ONLY the Ed25519 conjunct
  dropped (registry lookup, hex decode, and wire-width checks kept). Models
  "the signature no longer binds the message bytes" and nothing else.
* `M_gate[G]` — `mutantStep` with gate `G` forced true. Models "gate G is
  disabled".

A control's **sensitivity profile** is (flips-under-M_sig, {gates whose
M_gate flips it}). The mechanical adequacy check `profileMatches`:

* `.signature` ⇒ flips under M_sig AND flips under NO gate mutant. (An honest
  signature control's forged envelope has an INVALID signature, so disabling
  any gate cannot rescue it; only restoring signature acceptance can.)
* `.gate G`   ⇒ does NOT flip under M_sig AND flips under exactly M_gate[G].
  (A gate red carries a VALID signature; only its own gate blocks, so only
  disabling that gate flips it — and the signature mutant is inert.)
* `.registry` ⇒ flips under neither (kept out of the signature/gate scoring;
  witnessed separately by `verifyEffect` fail-closed — `M_sig` deliberately
  keeps the registry lookup, so an unregistered id stays blocked).

A control whose profile does not match its declared reason is *passing for the
wrong reason* — the machine form of frisk F1.
-/

open SealV2 SealV2.Effect Test.V2ValidationFixtures

namespace Test.FieldWarrant

-- generated by test/v2/field_warrant_sign_fixture.py (encoder twin
-- self-checked against the EffectEnvelope.lean golden-vector pins)
def sigBase : String :=
  "6893f0ee487f50cf7e8e2db20013c2c56615bf198f64be7083b1f85d720722e3b3c7ec6e98de94b4b4f70921229189192eea9f9eea8cbafc8b26a9e5301c1803"
/-- adapterType := "cli" — trips adapterGate. -/
def sigAdapterType : String :=
  "9889efeadc842b323cf8af875caa6691f7e8108e4e73007f58e2e762e803054950c8c5ef3c137619137b7e699470d02bd8b2f297d4eae4265e1a198c4e66ea09"
/-- adapterVersion := "9999-01-01" — trips adapterGate. -/
def sigAdapterVersion : String :=
  "23a1ab8b83a70306c68c24937e05ed92db02193a728a98a72bf90cba1d1e43eeb3f81ef62347c6abb6e3dfc19c9411c3f56912376031c40dd82977a522708605"
/-- session := "" — trips sessionGate (mandatory; the killed bypass). -/
def sigEmptySession : String :=
  "885368923600e4aca125cc7ced78eaab238a35a80b836674ca873b99eee7ca8e655b6ef1dc58bafe1888cc330cb51d510b7ef418a310eb8f321aee786424ac0e"
/-- session := "session-2" — trips sessionGate. -/
def sigSession : String :=
  "2ba0ec5e1e66e26848759a738c793d961ae1bedca6d7bc37eaa648c98d70873d78273e0e3eb1c28cacb1364678b6043b3c7f3de82f26ba7c614c55e853a8ba0d"
/-- policyVersion := "" — trips policyVersionGate (mandatory; killed bypass). -/
def sigEmptyPolicyVersion : String :=
  "08fb7990b8453a61360603aa077dbaa2784e969c94dfca21ffac2c4a879d390060b3ee28c64d0a4f200fbf6b68bc2a1bdaa2a8c5ad31ca208a339187e5696500"
/-- policyVersion := "policy-2" — trips policyVersionGate. -/
def sigPolicyVersion : String :=
  "c7c6217006f883b52fd5e8fcefd1b0d57cbf35815ec6e5822e2118f6f4f8abe12ebbee7c0a2a84bba5b33c01695c2e7da5932eda74501c9a500201010db40805"
/-- expiresAt := 0 — trips expiryGate (mandatory; the killed 0=unset seat). -/
def sigZeroExpiry : String :=
  "0d77dea67a8fe01264063162bcd3defbadd7b3d8bf3f4694804d1dafc69606cf0b44a0295208ac76ec423ffccb94c56368a02c1c2c8809159cc55cb9a774ba02"
/-- expiresAt := 1 (< now) — trips expiryGate. -/
def sigExpired : String :=
  "852f13304d8871b05cf54ed5ea35f874d5387a401226099271a684d25bb384312bcfd739db15f36fbcbede7e37db847658fe0d43883ae15bd063a1a910d72f04"
/-- issuedAt := 11 (> now) — trips issuedAtGate. -/
def sigFutureIssued : String :=
  "b2fd3701b8124e0fcb4993b99a9ed7bcb8c11a4252b2a38a6791f34fed0222dcbed63c197718ddb0eb88a00ce2ce323c826b96b27580c5477f151cdf835ef907"
/-- effect := some ⟨"", "", ""⟩ — the retired all-empty sentinel is now a
    PRESENT claim; trips effectGate on mismatch with the derived effect. -/
def sigEmptyStringClaim : String :=
  "9ba8b87f9dab6884ffa235485f0531aff55ae49902e0fe6a00a69780eff1e939c25fb8610e8a2bf73f71ea53b8f109e66fbfdaa76f6bbc6e6ff8295e1029360c"
/-- effect.resource := "fs.read" — trips effectGate. -/
def sigEffectResource : String :=
  "d7d995a9984631935adaae8e374ecc586e607788e253bf30f2132679051a69c94ace6c14fb1ac641193f7cd5bfd374de5e2043f2a39f7ba6eb6a89b871df950a"
/-- effect.action := "delete" — trips effectGate. -/
def sigEffectAction : String :=
  "e435f67c56a972708a004d18a175202f0d7cc4e223d3746ddc27b44a24742669f12823ed5cfa870b8a8c932072b56c513cde7490392ca1a2ecc967634d2dd105"
/-- effect.args amount 12.34→99 — trips effectGate. -/
def sigEffectArgs : String :=
  "2b1b97a84c8270e2f54f693308b3b378d4a3f32795ebda2ec85a69b188d29773a471b54b8ec7fc4549618faa75b91e67b6941df3db7eb9095f427bce4fa35a01"
/-- line swapped to an fs.read call — trips effectGate (kept F3 claim no
    longer derived from the judged line). -/
def sigLine : String :=
  "67b57afb15d1069996f9c3cf68f39d93e45e950af80a0d7bbc2882ae6b6077fbbaad767d6efbb1493037c845f4190c34e8f801804a8403006928b13216e75c0e"
/-- GREEN #2: effect := none — F3 DECLARED absent (signed presence byte). -/
def sigNoEffectClaim : String :=
  "4fd479259a1a2cb01af30c59f2bdba3d1d32350f37b89fe1d99330034a1fc2fc22b3a1ce91123ea8cce38477908eba17782f76afa76ff49741768419dc40c70d"

def authority : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (0xa0 + i))

def envNonce : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map UInt8.ofNat)

def registry : PrincipalRegistry :=
  [{ id := "alice", pubkey := testPublicKeyHex }]

/-- Twin registry for the keyId SIGNATURE RED: `alice2` is REGISTERED with
    the SAME pubkey, so the registry lookup succeeds and fail-closed cannot
    be the discriminator — only the signature over `frame(keyId)` can. -/
def registryTwin : PrincipalRegistry :=
  [{ id := "alice", pubkey := testPublicKeyHex },
   { id := "alice2", pubkey := testPublicKeyHex }]

def mediator : AdapterId := { type := "mcp", version := "2025-06-18" }

def baseArgs : String := "{\"database\":\"prod\",\"table\":\"users\",\"amount\":12.34}"

def baseClaim : EffectClaim :=
  { resource := "db.execute", action := "write", args := baseArgs,
    metadata := .absent }

/-- The warrant base: passes every gate against the fixture `baseState`
    (session-1, now=10, policy-1, ttl cap 300) with every mandatory binding
    populated and the F3 claim PRESENT. `line` is the fixture's `validRaw`,
    which `decide` Allows in `baseState`. -/
def baseEnvelope : EffectEnvelope :=
  { keyId := "alice"
    nonce := envNonce
    issuedAt := 5
    expiresAt := 100
    line := validRaw
    adapterType := "mcp"
    adapterVersion := "2025-06-18"
    session := "session-1"
    policyVersion := "policy-1"
    effect := some baseClaim }

/-- The SECOND canonical mint anchor: the declared-absent green (GREEN #2 in
    the SHOW suite — `effect := none`, signed presence byte). `sigNoEffectClaim`
    is its honest signature. Together with `baseEnvelope`/`sigBase` these are
    the ONLY diff bases a `.signature` control may measure against
    (frisk F-ADEQ-1 repair — see `mintAnchors`). -/
def absentAnchor : EffectEnvelope := { baseEnvelope with effect := none }

/-- The old suite's line forgery / gate-red line: swaps to an fs.read call,
    so `deriveEffect` changes and `effectGate` trips. -/
def swappedLine : String :=
  "{\"method\":\"tools/call\",\"params\":{\"name\":\"fs.read\",\"action\":\"read\",\"arguments\":{}}}"

/-- The isolating line forgery: a WHITESPACE variant of `validRaw` (a space
    after `tools/call,`). Parses to the identical AST, so `deriveEffect` and
    the decision are unchanged and `effectGate` passes; only the signed BYTES
    differ. -/
def spacedRaw : String :=
  "{\"method\":\"tools/call\", \"params\":{\"name\":\"db.execute\",\"action\":\"write\",\"arguments\":{\"database\":\"prod\",\"table\":\"users\",\"amount\":12.34}}}"

def tamperedArgs : String :=
  "{\"database\":\"prod\",\"table\":\"users\",\"amount\":99}"

def emptyClaimEnv : EffectEnvelope :=
  { baseEnvelope with
    effect := some { resource := "", action := "", args := "", metadata := .absent } }

def forgedNonce : ByteArray :=
  ByteArray.mk (Array.range 32 |>.map fun i => UInt8.ofNat (i + 1))

/-! ## Mutation machinery -/

/-- The six gates, as a selector. -/
inductive GateSel
  | adapter | session | effect | expiry | issuedAt | policyVersion
  deriving DecidableEq, Repr, BEq

def GateSel.name : GateSel → String
  | .adapter => "adapterGate"
  | .session => "sessionGate"
  | .effect => "effectGate"
  | .expiry => "expiryGate"
  | .issuedAt => "issuedAtGate"
  | .policyVersion => "policyVersionGate"

def allGates : List GateSel :=
  [.adapter, .session, .effect, .expiry, .issuedAt, .policyVersion]

/-- The reason a negative control asserts its Block. -/
inductive Reason
  | signature | gate (g : GateSel) | registry
  deriving DecidableEq, Repr, BEq

def Reason.describe : Reason → String
  | .signature => "signature"
  | .gate g => s!"gate:{g.name}"
  | .registry => "registry"

/-- One step-executing negative control, as DATA — the single source both the
    human suite and the mutation harness consume. `field` is the signed field
    whose warrant this control serves; `reason` is what its Block is claimed
    to measure. -/
structure Control where
  name : String
  field : String
  e : EffectEnvelope
  sig : String
  st : ApprovalState
  med : AdapterId
  reg : PrincipalRegistry
  reason : Reason
  /-- The envelope this control's `sig` was actually MINTED over — the diff
      base for the DERIVED perturbation set (frisk F-HARNESS-1 repair). NOT a
      free choice: `sigAdequate` pins `(mintedE, sig)` to one of the TWO
      canonical anchors (`mintAnchors`), because with a free `mintedE` the
      author steers the credited field at will — the diff of two authored
      envelopes is itself authored (frisk F-ADEQ-1, ATTACK-D). Gate/registry
      rows ignore it (their sig signs `e` itself; their perturbation is
      measured against `baseEnvelope`). -/
  mintedE : EffectEnvelope := baseEnvelope

/-- Real value of a named gate for a control's envelope + verifier config. -/
def gateValue : GateSel → AdapterId → ApprovalState → EffectEnvelope → Bool
  | .adapter, m, _, e => adapterGate m e
  | .session, _, s, e => sessionGate s e
  | .effect, m, _, e => effectGate m e
  | .expiry, _, s, e => expiryGate s e
  | .issuedAt, _, s, e => issuedAtGate s e
  | .policyVersion, _, s, e => policyVersionGate s e

/-- `verifyEffect` with ONLY the Ed25519 conjunct dropped — registry lookup,
    hex decode, authority/pubkey width, and wire-width checks all kept. Models
    "the signature no longer binds the message bytes" and nothing else. Returns
    a Bool (whether verification would succeed); never constructs the
    private-ctor `AuthenticatedId`. -/
def verifyNoSig (auth : ByteArray) (reg : PrincipalRegistry)
    (e : EffectEnvelope) (sig : String) : Bool :=
  match reg.find? (fun k => k.id == e.keyId) with
  | none => false
  | some k =>
      match hexDecode? k.pubkey, hexDecode? sig with
      | some pk, some _ => auth.size == 32 && pk.size == 32 && wireSizedB e
      | _, _ => false

/-- `effectStep` under a mutant: optionally drop the Ed25519 signature check
    (`neuterSig`) and/or force a set of gates true (`disabled`). With
    `neuterSig = false, disabled = []` this equals `effectStep`. -/
def mutantStep (neuterSig : Bool) (disabled : List GateSel)
    (auth : ByteArray) (reg : PrincipalRegistry) (med : AdapterId)
    (e : EffectEnvelope) (sig : String) (st : ApprovalState) : Decision :=
  let verified := if neuterSig then verifyNoSig auth reg e sig
                  else (verifyEffect auth reg e sig).isSome
  if verified then
    if allGates.all (fun g => disabled.contains g || gateValue g med st e) then
      SealV2.decide e.line st
    else .Block
  else .Block

def outAllow : Decision → Bool
  | .Allow _ => true
  | .Block => false

def Control.baseOutcome (c : Control) : Bool :=
  outAllow (mutantStep false [] authority c.reg c.med c.e c.sig c.st)

def Control.flipSig (c : Control) : Bool :=
  outAllow (mutantStep true [] authority c.reg c.med c.e c.sig c.st) != c.baseOutcome

def Control.flipGate (c : Control) (g : GateSel) : Bool :=
  outAllow (mutantStep false [g] authority c.reg c.med c.e c.sig c.st) != c.baseOutcome

def Control.sensGates (c : Control) : List GateSel :=
  allGates.filter c.flipGate

/-- The gates that are actually FALSE for this control's envelope + config. -/
def Control.gateFalseSet (c : Control) : List GateSel :=
  allGates.filter (fun g => gateValue g c.med c.st c.e == false)

/-- Disabling ALL of the control's failing gates flips it to Allow — i.e. the
    gates are the ONLY thing blocking (not a bad signature, not the registry).
    Robust to OVERDETERMINED gate reds (e.g. the stale row, which trips both
    `issuedAt` and `expiry` at once) where disabling a single gate is not
    enough to flip. -/
def Control.gatesAreSoleBlocker (c : Control) : Bool :=
  outAllow (mutantStep false c.gateFalseSet authority c.reg c.med c.e c.sig c.st)

/-- The mechanical adequacy check: does the control's sensitivity profile
    match its declared reason? A `false` here is a control passing for the
    wrong reason — the machine form of frisk F1.

    * `.signature` — flips under the signature mutant AND under NO gate mutant.
    * `.gate g` — inert under the signature mutant, `g` is genuinely a failing
      gate, and the failing gates are the sole blocker (so a gate red hiding a
      bad signature — which would NOT flip when its gates are disabled — is
      caught here, mirroring the suite's `sigVerifies=true` assertion). This
      form accepts overdetermined gate reds without demanding single-gate
      isolation the base envelope cannot provide.
    * `.registry` — inert under both mutants (`verifyNoSig` keeps the registry
      lookup, so an unregistered id stays blocked); witnessed separately by
      `verifyEffect` fail-closed. -/
def Control.profileMatches (c : Control) : Bool :=
  match c.reason with
  | .signature => c.flipSig && c.sensGates.isEmpty
  | .gate g => (!c.flipSig) && c.gateFalseSet.contains g && c.gatesAreSoleBlocker
  | .registry => (!c.flipSig) && c.sensGates.isEmpty && (!c.gatesAreSoleBlocker)

/-! ## Derived perturbation (frisk F-HARNESS-1 repair, hardened per F-ADEQ-1)

The claim-list join used to key on `Control.field` — an UNVERIFIED string —
so a genuine signature red could claim credit for a field it never touches
(the frisk's DISHONEST-A). First repair: DERIVE the perturbed field set by
diffing the presented envelope against the envelope the signature was minted
over, and key the join on that derived set. That MOVED the trust root rather
than removing it: `mintedE` was author-supplied, so the diff of two authored
envelopes was itself authored (frisk F-ADEQ-1, ATTACK-D fabricated a witness
for the declared session gap). Second repair: pin the diff base to the two
canonical `mintAnchors`, pin the registry keys, and structurally exclude
named-gap fields from credit — the credited field is now a function of the
presented envelope and validated corpus-singleton constants only. -/

/-- Field-labelled diff of the F3 claim seat (presence flip first). -/
def claimDiff : Option EffectClaim → Option EffectClaim → List String
  | none, none => []
  | some _, none => ["effectPresence"]
  | none, some _ => ["effectPresence"]
  | some a, some b =>
      (if a.resource != b.resource then ["effect.resource"] else []) ++
      (if a.action != b.action then ["effect.action"] else []) ++
      (if a.args != b.args then ["effect.args"] else []) ++
      (if a.metadata != b.metadata then ["effect.metadata"] else [])

/-- Field-labelled diff of two envelopes: one label per signed seat that
    differs. Completeness against structure growth is NOT assumed here — the
    `patchField` roundtrip in `sigAdequate` closes that hole mechanically. -/
def envDiff (e base : EffectEnvelope) : List String :=
  (if e.keyId != base.keyId then ["keyId"] else []) ++
  (if e.nonce != base.nonce then ["nonce"] else []) ++
  (if e.issuedAt != base.issuedAt then ["issuedAt"] else []) ++
  (if e.expiresAt != base.expiresAt then ["expiresAt"] else []) ++
  (if e.line != base.line then ["line"] else []) ++
  (if e.adapterType != base.adapterType then ["adapterType"] else []) ++
  (if e.adapterVersion != base.adapterVersion then ["adapterVersion"] else []) ++
  (if e.session != base.session then ["session"] else []) ++
  (if e.policyVersion != base.policyVersion then ["policyVersion"] else []) ++
  claimDiff e.effect base.effect

/-- Copy ONE named signed field from `src` onto `dst`; `none` for an unknown
    label. Used by the roundtrip check: patching the single derived field onto
    the minted envelope must reproduce the forgery under the DERIVED `BEq`
    over the WHOLE structure — so a field `envDiff` cannot see (e.g. a seat
    added to `EffectEnvelope` later without updating `envDiff`) cannot hide a
    second perturbation. -/
def patchField (f : String) (src dst : EffectEnvelope) : Option EffectEnvelope :=
  match f with
  | "keyId" => some { dst with keyId := src.keyId }
  | "nonce" => some { dst with nonce := src.nonce }
  | "issuedAt" => some { dst with issuedAt := src.issuedAt }
  | "expiresAt" => some { dst with expiresAt := src.expiresAt }
  | "line" => some { dst with line := src.line }
  | "adapterType" => some { dst with adapterType := src.adapterType }
  | "adapterVersion" => some { dst with adapterVersion := src.adapterVersion }
  | "session" => some { dst with session := src.session }
  | "policyVersion" => some { dst with policyVersion := src.policyVersion }
  | "effectPresence" => some { dst with effect := src.effect }
  | "effect.resource" =>
      match src.effect, dst.effect with
      | some s, some d => some { dst with effect := some { d with resource := s.resource } }
      | _, _ => none
  | "effect.action" =>
      match src.effect, dst.effect with
      | some s, some d => some { dst with effect := some { d with action := s.action } }
      | _, _ => none
  | "effect.args" =>
      match src.effect, dst.effect with
      | some s, some d => some { dst with effect := some { d with args := s.args } }
      | _, _ => none
  | "effect.metadata" =>
      match src.effect, dst.effect with
      | some s, some d =>
          some { dst with effect := some { d with metadata := s.metadata } }
      | _, _ => none
  | _ => none

/-- Signed material with NO step-level signature witness — the NAMED GAPS, each
    with its REASON. Witnessed instead by MESSAGE DISTINCTNESS (recomputed in
    the mutation harness) plus the kernel injectivity proofs. Listed EXPLICITLY
    so the gap renders rather than hides — and consumed by `sigAdequate`'s GAP
    EXCLUSION: a field the harness admits is un-witnessable can NEVER be
    credited by a signature control (frisk F-ADEQ-1 repair). Lives here, with
    the corpus, so the exclusion and the partition read the SAME list.

    * `authority` — not an `EffectEnvelope` field (config trust root threaded
      separately); no per-field step forgery to construct.
    * `effect.resource/action/args/metadata` — `effectGate` pins a present claim to
      `deriveEffect` of the UNCHANGED signed line, so no verifier config makes
      the gate pass while only a sub-field's signature discriminates.
    * `session` — coupled into the decision layer's SIGNED approval
      (`approvalLiveFor` re-verifies the approval, which covers session), so no
      state alignment isolates the envelope signature at the step without
      minting a fresh approval fixture. -/
def encodingOnlyFields : List (String × String) :=
  [ ("authority", "not an envelope field")
  , ("effect.resource", "effectGate pins claim to deriveEffect(line)")
  , ("effect.action", "effectGate pins claim to deriveEffect(line)")
  , ("effect.args", "effectGate pins claim to deriveEffect(line)")
  , ("effect.metadata", "effectGate pins claim to deriveEffect(line)")
  , ("session", "coupled to decide's signed approval") ]

/-- The TWO canonical mint anchors — the ONLY `(mintedE, sig)` pairs a
    `.signature` control may measure its perturbation against: the strong-form
    green and the declared-absent green, each with its honest signature. Both
    are re-validated GREEN (sig verifies, all gates pass, step Allows under the
    canonical config) by the mutation harness's ANCHOR VALIDATION section.

    This pin is the F-ADEQ-1 repair's load-bearing move: with `mintedE` free,
    "carries a verifying signature" is satisfiable by unlimited distinct
    envelopes (public test seed), so the credited field
    `envDiff c.e c.mintedE` was a pure function of the author's `mintedE`
    choice. Pinned, the credited field is a function of `c.e` and a validated
    corpus-singleton constant — the frisk's own criterion. An anchor cannot be
    corrupted selectively: breaking one breaks the green check for the whole
    corpus, not just one field's credit. -/
def mintAnchors : List (EffectEnvelope × String) :=
  [(baseEnvelope, sigBase), (absentAnchor, sigNoEffectClaim)]

/-- The reference envelope a control's perturbation is measured against:
    the signature's true preimage for `.signature` rows (mint-checked in
    `sigAdequate`), the warrant base for gate/registry rows (whose own sig
    signs `e` itself). -/
def Control.diffBase (c : Control) : EffectEnvelope :=
  match c.reason with
  | .signature => c.mintedE
  | _ => baseEnvelope

/-- The DERIVED perturbed-field set — what the control actually touches,
    computed from envelope bytes, not read off a label. -/
def Control.perturbedFields (c : Control) : List String :=
  envDiff c.e c.diffBase

/-- ADEQUACY for a `.signature` control, v3 — the label is derived-checked and
    the diff base is PINNED, never authored (frisk F-HARNESS-1 + F-ADEQ-1):

    1. **Anchor pin** — `(mintedE, sig)` is one of the two canonical
       `mintAnchors`. Kills ATTACK-D/E: the author no longer chooses the other
       side of the diff, so the credited field is a function of `c.e` alone.
    2. **Key pin** — every registry entry carries the canonical test pubkey,
       so mint validity cannot be met with an attacker-generated keypair
       (frisk F-ADEQ-2).
    3. **Mint validity** — `sig` genuinely verifies over `mintedE` under the
       control's own registry (kills A2-style invented preimages, and with
       the pins above it now means: a true signature over a canonical green).
    4. **Singleton** — the forgery differs from the anchor in EXACTLY ONE
       derived field, and that field is the declared one;
    5. **Gap exclusion** — that field is NOT a declared named gap: a field the
       harness admits is un-witnessable at the step level can never be
       credited, so the named-gap machinery is structurally undefeatable.
    6. **Patch roundtrip** — copying that single field from the forgery onto
       the anchor reproduces the forgery under whole-structure `BEq`, so a
       seat `envDiff` misses cannot smuggle a second perturbation;
    7. **Bytes move** — the signed message bytes actually differ, tying the
       perturbation to the signature domain. -/
def Control.sigAdequate (c : Control) : Bool :=
  let anchorPinned := mintAnchors.any (fun a => c.mintedE == a.1 && c.sig == a.2)
  let keysPinned := c.reg.all (fun k => k.pubkey == testPublicKeyHex)
  let mintValid := (verifyEffect authority c.reg c.mintedE c.sig).isSome
  let singleton :=
    match envDiff c.e c.mintedE with
    | [f] =>
        f == c.field &&
        !(encodingOnlyFields.map (·.1)).contains f &&
        (match patchField f c.e c.mintedE with
         | some patched => patched == c.e
         | none => false)
    | _ => false
  let bytesMove := effectMessage authority c.e != effectMessage authority c.mintedE
  anchorPinned && keysPinned && mintValid && singleton && bytesMove

/-- Label adequacy for the WHOLE corpus. `.signature` rows get the full
    derived check; gate/registry rows must at least name a field they
    genuinely perturb relative to the warrant base (`effect.claim` is the
    umbrella label for the all-empty claim row, where every sub-field moves
    at once). -/
def Control.fieldAdequate (c : Control) : Bool :=
  match c.reason with
  | .signature => c.sigAdequate
  | _ =>
      let d := envDiff c.e baseEnvelope
      d.contains c.field ||
      (c.field == "effect.claim" && !d.isEmpty && d.all (·.startsWith "effect."))

/-! ## Generated signature rows (frisk F-ADEQ-1 repair, declaration removal)

A `.signature` control used to DECLARE its label, its diff base and its mint
signature — three authored objects checked only against each other, so each
frisk moved the trust root one object over. The generated form removes the
attribution-bearing declarations: a seed authors ONLY the perturbation and the
verifier-side config alignment; the label, diff base and mint signature are
OUTPUTS. The seed cannot lie about attribution — `field := envDiff e anchor`
by construction — and it cannot fake a witness, because credit still requires
the execution-measured sensitivity profile, which no input choice can forge
for a gap-coupled field (that impossibility is exactly why the named gaps are
gaps). The checks (`sigAdequate` etc.) remain authoritative over ANY `Control`
value, generated or hand-built: generation shrinks the authored surface, the
checks defend it. -/

/-- Seed for ONE generated signature control. Authored inputs: the seat
    perturbation (values must dodge the gates — e.g. issuedAt 6 stays inside
    the freshness window) and the config alignment that lets every gate pass
    over the forgery. Nothing here names a field or a mint base. -/
structure SigSeed where
  note : String := ""
  tweak : EffectEnvelope → EffectEnvelope
  st : ApprovalState := baseState
  med : AdapterId := mediator
  reg : PrincipalRegistry := registry
  /-- Ride the declared-absent anchor (GREEN #2) instead of the strong form. -/
  absentForm : Bool := false

/-- Generate the control: anchor and mint signature come from the pinned
    `mintAnchors` pair selected by `absentForm`; the label is DERIVED from the
    diff. A seed whose tweak does not produce a singleton diff poisons its own
    label (`NON-SINGLETON-SEED:…`), which fails `sigAdequate`/`fieldAdequate`
    LOUDLY in the harness instead of vanishing. -/
def genSigControl (s : SigSeed) : Control :=
  let (anchor, sig) := if s.absentForm then (absentAnchor, sigNoEffectClaim)
                       else (baseEnvelope, sigBase)
  let e := s.tweak anchor
  let field := match envDiff e anchor with
    | [f] => f
    | d => s!"NON-SINGLETON-SEED:{d}"
  { name := s!"forged {field}{if s.note.isEmpty then "" else s!" ({s.note})"}"
    field, e, sig
    st := s.st, med := s.med, reg := s.reg
    reason := .signature, mintedE := anchor }

/-- The ten signature-red seeds — same envelopes, configs and coverage as the
    previous hand-written rows, minus the authored label/base/mint.
    NO session seed: session is coupled into the decision layer's SIGNED
    approval (`approvalLiveFor` re-verifies the approval, which covers
    session). Aligning `sessionGate` desyncs that approval, so `decide` blocks
    independently of the envelope signature — no seed can pass the profile
    without minting a fresh approval fixture. Named gap; witnessed at the
    encoding level instead (`bytes[session]` + `effect_message_injective`),
    and structurally excluded from credit by `sigAdequate`. -/
def sigSeeds : List SigSeed :=
  [ { note := "alice2 twin-registered, same pubkey"
      tweak := fun a => { a with keyId := "alice2" }, reg := registryTwin }
  , { note := "+1 bytes"
      tweak := fun a => { a with nonce := forgedNonce } }
  , { note := "6, still in freshness window"
      tweak := fun a => { a with issuedAt := 6 } }
  , { note := "101, still unexpired, nonzero"
      tweak := fun a => { a with expiresAt := 101 } }
  , { note := "whitespace variant, same derived effect"
      tweak := fun a => { a with line := spacedRaw } }
  , { note := "mcp2, mediator aligned, absent-form base"
      tweak := fun a => { a with adapterType := "mcp2" }
      med := { type := "mcp2", version := "2025-06-18" }, absentForm := true }
  , { note := "2025-06-19, mediator aligned"
      tweak := fun a => { a with adapterVersion := "2025-06-19" }
      med := { type := "mcp", version := "2025-06-19" } }
  , { note := "policy-1x, state aligned"
      tweak := fun a => { a with policyVersion := "policy-1x" }
      st := { baseState with policyVersion := "policy-1x" } }
  , { note := "presence flip some→none"
      tweak := fun a => { a with effect := none } }
  , { note := "presence flip none→some"
      tweak := fun a => { a with effect := some baseClaim }, absentForm := true } ]

/-- **The authoritative negative-control corpus** — every step-executing row of
    the SHOW suite, as data. 13 gate reds, 1 registry fail-closed, 10 GENERATED
    signature reds. The two GREEN positives and the pure-encoding MESSAGE
    DISTINCTNESS rows are not here: greens are not negative controls, and the
    byte rows do not execute a step (they compare `effectMessage` bytes
    directly). -/
def corpus : List Control :=
  -- GATE REDS (valid signature, one gate tripped)
  [ { name := "adapterType=cli", field := "adapterType"
      e := { baseEnvelope with adapterType := "cli" }, sig := sigAdapterType
      st := baseState, med := mediator, reg := registry, reason := .gate .adapter }
  , { name := "adapterVersion=9999-01-01", field := "adapterVersion"
      e := { baseEnvelope with adapterVersion := "9999-01-01" }, sig := sigAdapterVersion
      st := baseState, med := mediator, reg := registry, reason := .gate .adapter }
  , { name := "session=\"\"", field := "session"
      e := { baseEnvelope with session := "" }, sig := sigEmptySession
      st := baseState, med := mediator, reg := registry, reason := .gate .session }
  , { name := "session=session-2", field := "session"
      e := { baseEnvelope with session := "session-2" }, sig := sigSession
      st := baseState, med := mediator, reg := registry, reason := .gate .session }
  , { name := "policyVersion=\"\"", field := "policyVersion"
      e := { baseEnvelope with policyVersion := "" }, sig := sigEmptyPolicyVersion
      st := baseState, med := mediator, reg := registry, reason := .gate .policyVersion }
  , { name := "policyVersion=policy-2", field := "policyVersion"
      e := { baseEnvelope with policyVersion := "policy-2" }, sig := sigPolicyVersion
      st := baseState, med := mediator, reg := registry, reason := .gate .policyVersion }
  , { name := "expiresAt=0", field := "expiresAt"
      e := { baseEnvelope with expiresAt := 0 }, sig := sigZeroExpiry
      st := baseState, med := mediator, reg := registry, reason := .gate .expiry }
  , { name := "expiresAt=1 (past)", field := "expiresAt"
      e := { baseEnvelope with expiresAt := 1 }, sig := sigExpired
      st := baseState, med := mediator, reg := registry, reason := .gate .expiry }
  , { name := "issuedAt=11 (future)", field := "issuedAt"
      e := { baseEnvelope with issuedAt := 11 }, sig := sigFutureIssued
      st := baseState, med := mediator, reg := registry, reason := .gate .issuedAt }
  , { name := "effect=some(\"\",\"\",\"\")", field := "effect.claim"
      e := emptyClaimEnv, sig := sigEmptyStringClaim
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  , { name := "effect.resource=fs.read", field := "effect.resource"
      e := { baseEnvelope with effect := some { baseClaim with resource := "fs.read" } }
      sig := sigEffectResource
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  , { name := "effect.action=delete", field := "effect.action"
      e := { baseEnvelope with effect := some { baseClaim with action := "delete" } }
      sig := sigEffectAction
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  , { name := "effect.args amount=99", field := "effect.args"
      e := { baseEnvelope with effect := some { baseClaim with args := tamperedArgs } }
      sig := sigEffectArgs
      st := baseState, med := mediator, reg := registry, reason := .gate .effect }
  -- REGISTRY fail-closed (no gate; verifyEffect none on unregistered id)
  , { name := "keyId=mallory (unregistered)", field := "keyId"
      e := { baseEnvelope with keyId := "mallory" }, sig := sigBase
      st := baseState, med := mediator, reg := registry, reason := .registry } ]
  -- SIGNATURE REDS (all gates pass, only the signature blocks) — GENERATED:
  -- label, diff base and mint signature are outputs of `genSigControl`, not
  -- authored row data (frisk F-ADEQ-1 repair).
  ++ sigSeeds.map genSigControl

/-- The HAND-AUTHORED adequacy claim: every signed field that must carry a
    step-level signature witness. Lives with the corpus so both the mutation
    harness and the dishonest-control probe join against the SAME list; still
    hand-authored, independent of the corpus rows. The mutation harness's
    COVERAGE PARTITION cross-checks it against every label `envDiff` can emit,
    so dropping an entry fails LOUDLY instead of silently shrinking coverage
    (frisk F-HARNESS-2). -/
def requiredSignatureFields : List String :=
  ["keyId", "nonce", "issuedAt", "expiresAt", "line", "adapterType",
   "adapterVersion", "policyVersion", "effectPresence"]

/-- The naive one-signature forgery for a field, reusing `sigBase` against the
    base verifier config — the OLD (pre-F1) control shape. Used only by the
    frisk-reproduction section of the mutation harness. -/
def naiveForgery (field : String) (e : EffectEnvelope) (sig : String := sigBase) : Control :=
  { name := s!"naive forged {field}", field, e, sig
    st := baseState, med := mediator, reg := registry, reason := .signature }

/-- The pre-F1 forgery corpus the frisk analysed: forge one field, reuse the
    base signature, expect Block, CLAIM signature binding. Nine of these
    fourteen pass for the wrong reason; the mutation harness recounts it. -/
def naiveCorpus : List Control :=
  [ naiveForgery "keyId" { baseEnvelope with keyId := "alice2" }
  , naiveForgery "nonce" { baseEnvelope with nonce := forgedNonce }
  , naiveForgery "issuedAt" { baseEnvelope with issuedAt := 6 }
  , naiveForgery "expiresAt" { baseEnvelope with expiresAt := 101 }
  , naiveForgery "line" { baseEnvelope with line := swappedLine }
  , naiveForgery "adapterType" { baseEnvelope with adapterType := "mcp2" }
  , naiveForgery "adapterVersion" { baseEnvelope with adapterVersion := "2025-06-19" }
  , naiveForgery "session" { baseEnvelope with session := "session-1x" }
  , naiveForgery "policyVersion" { baseEnvelope with policyVersion := "policy-1x" }
  , naiveForgery "effect.resource"
      { baseEnvelope with effect := some { baseClaim with resource := "db.executex" } }
  , naiveForgery "effect.action"
      { baseEnvelope with effect := some { baseClaim with action := "writex" } }
  , naiveForgery "effect.args"
      { baseEnvelope with effect := some { baseClaim with args := "{}" } }
  , naiveForgery "effectPresence" { baseEnvelope with effect := none }
  , { naiveForgery "effectPresence" baseEnvelope sigNoEffectClaim with
      name := "naive forged effectPresence none→some" } ]

end Test.FieldWarrant
