// SPDX-License-Identifier: Apache-2.0
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE_SCRIPT = path.join(ROOT, "scripts/linkcheck.mjs");
const SOURCE_PARSER = path.join(ROOT, "scripts/vendor/commonmark.cjs");
const POPULATION_RELATIVE = "test/support/linkcheck-population.mjs";
const FAMILY = [
  "seal-check",
  "seal-demo",
  "seal-live-demo",
  "seal-verify-action",
  "seal-assurance-kit",
  "mcp-seal-dev",
];

function sha256(file) {
  return createHash("sha256").update(readFileSync(file)).digest("hex");
}

function counts(internalOccurrences, externalOccurrences = 0) {
  return { internalOccurrences, externalOccurrences };
}

function populationSource({ fileOccurrences, fileOccurrencesHighWaterMarks = fileOccurrences, internalOccurrences }) {
  return [
    "// Generated by node scripts/linkcheck.mjs --write; review by rerunning that command.",
    "// The separate-source target cross-check lives in test/linkcheck.test.mjs and",
    "// cannot be refreshed from LINKCHECK_REPORT_SCANNED_TARGETS. It is deliberately",
    "// described as a cross-check; docs/assurance/linkcheck-population-control.md",
    "// records its shared blind spots.",
    "// High-water marks never move down automatically; accepted shrink history stays review-visible.",
    "export default {",
    "  populationRule: 1,",
    `  internalOccurrences: ${internalOccurrences},`,
    "  externalOccurrences: 0,",
    `  internalOccurrencesHighWaterMark: ${internalOccurrences},`,
    "  externalOccurrencesHighWaterMark: 0,",
    `  fileOccurrences: ${JSON.stringify(fileOccurrences, null, 2).replace(/^/gm, "  ")},`,
    `  fileOccurrencesHighWaterMarks: ${JSON.stringify(fileOccurrencesHighWaterMarks, null, 2).replace(/^/gm, "  ")},`,
    "  shrinkHistory: [",
    "  ],",
    "};",
    "",
  ].join("\n");
}

function workspace({ pages, population }) {
  const space = mkdtempSync(path.join(tmpdir(), "seal-linkgen8-"));
  const runner = path.join(space, "runner");
  const tree = path.join(space, "tree");
  const script = path.join(runner, "scripts/linkcheck.mjs");
  const record = path.join(runner, POPULATION_RELATIVE);
  mkdirSync(path.dirname(script), { recursive: true });
  mkdirSync(path.join(runner, "scripts/vendor"), { recursive: true });
  mkdirSync(path.dirname(record), { recursive: true });
  mkdirSync(path.join(tree, "spine"), { recursive: true });
  for (const repo of FAMILY) mkdirSync(path.join(tree, ".family", repo), { recursive: true });
  copyFileSync(SOURCE_SCRIPT, script);
  copyFileSync(SOURCE_PARSER, path.join(runner, "scripts/vendor/commonmark.cjs"));
  writeFileSync(path.join(runner, "package.json"), "{\"type\":\"module\"}\n");
  writeFileSync(path.join(runner, "mock-fetch.mjs"), [
    "globalThis.fetch = async () => ({",
    "  ok: true,",
    "  body: { cancel: async () => {} },",
    "});",
    "",
  ].join("\n"));
  writeFileSync(record, population);
  writeFileSync(path.join(tree, "spine/demo.cjs"), "// https://velvetmonkey.github.io/seal-check/\n");
  for (const [name, contents] of Object.entries(pages)) {
    const file = path.join(tree, name);
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, contents);
  }
  const run = (...args) => spawnSync(process.execPath, [
    "--import", path.join(runner, "mock-fetch.mjs"),
    script,
    "--write",
    ...args,
    "--root", tree,
  ], { cwd: runner, encoding: "utf8" });
  return {
    space,
    tree,
    record,
    run,
    cleanup: () => rmSync(space, { recursive: true, force: true }),
  };
}

function basicPages(readme = "Required https://velvetmonkey.github.io/seal-check/\n[one](target.md)\n") {
  return { "README.md": readme, "target.md": "target\n" };
}

function basicFiles(readmeCount = 1, extra = {}) {
  return {
    "README.md": counts(readmeCount),
    ...extra,
    "target.md": counts(0),
  };
}

function output(result) {
  return `${result.stdout}${result.stderr}`;
}

test("defect 1: a named shrink does not sequentially re-baseline an unflagged write", () => {
  const files = basicFiles(2);
  const space = workspace({
    pages: basicPages("Required https://velvetmonkey.github.io/seal-check/\n[one](target.md)\n[two](target.md)\n"),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 2 }),
  });
  try {
    writeFileSync(path.join(space.tree, "README.md"), basicPages()["README.md"]);
    const accepted = space.run("--allow-shrink", "README.md");
    assert.equal(accepted.status, 0, output(accepted));
    const unflagged = space.run();
    assert.equal(unflagged.status, 1, output(unflagged));
    assert.match(unflagged.stderr, /README\.md/);
  } finally {
    space.cleanup();
  }
});

test("defect 2: comments and duplicate keys cannot poison a recorded file count", () => {
  const files = basicFiles(1, { "loser.md": counts(1) });
  const base = populationSource({ fileOccurrences: files, internalOccurrences: 2 });
  const commentSpace = workspace({
    pages: { ...basicPages(), "loser.md": "[one](target.md)\n" },
    population: base.replace("export default {", "// loser.md internalOccurrences: 0\nexport default {"),
  });
  try {
    writeFileSync(path.join(commentSpace.tree, "loser.md"), "no links\n");
    writeFileSync(path.join(commentSpace.tree, "README.md"), `${basicPages()["README.md"]}[two](target.md)\n`);
    const result = commentSpace.run();
    assert.equal(result.status, 1, output(result));
  } finally {
    commentSpace.cleanup();
  }

  const duplicateEntry = [
    '    "loser.md": {',
    '      "internalOccurrences": 0,',
    '      "externalOccurrences": 0',
    "    },",
  ].join("\n");
  const recordedLoser = [
    '    "loser.md": {',
    '      "internalOccurrences": 1,',
    '      "externalOccurrences": 0',
    "    },",
  ].join("\n");
  const duplicateSpace = workspace({
    pages: { ...basicPages(), "loser.md": "no links\n" },
    population: base.replace(recordedLoser, `${recordedLoser}\n${duplicateEntry}`),
  });
  try {
    writeFileSync(path.join(duplicateSpace.tree, "README.md"), `${basicPages()["README.md"]}[two](target.md)\n`);
    const result = duplicateSpace.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /duplicate key.*loser\.md/);
  } finally {
    duplicateSpace.cleanup();
  }
});

test("defect 3: a compensating swap refuses and names the file that lost a link", () => {
  const files = basicFiles(1, { "loser.md": counts(1) });
  const space = workspace({
    pages: { ...basicPages(), "loser.md": "[one](target.md)\n" },
    population: populationSource({ fileOccurrences: files, internalOccurrences: 2 }),
  });
  try {
    writeFileSync(path.join(space.tree, "loser.md"), "no links\n");
    writeFileSync(path.join(space.tree, "README.md"), `${basicPages()["README.md"]}[two](target.md)\n`);
    const result = space.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /loser\.md/);
  } finally {
    space.cleanup();
  }
});

test("defect 4: an absent, empty, or wrong-typed record refuses", () => {
  const files = basicFiles();
  const source = populationSource({ fileOccurrences: files, internalOccurrences: 1 });
  for (const variant of ["absent", "empty", "wrong-typed"]) {
    const space = workspace({ pages: basicPages(), population: source });
    try {
      if (variant === "absent") rmSync(space.record);
      else if (variant === "empty") writeFileSync(space.record, "");
      else writeFileSync(space.record, "export default [];\n");
      const result = space.run();
      assert.equal(result.status, 1, `${variant}: ${output(result)}`);
      assert.match(output(result), /REFUSE/, `${variant} must be a named refusal`);
    } finally {
      space.cleanup();
    }
  }
});

test("defect 5: a record that omits a recorded link-bearing file refuses", () => {
  const files = basicFiles(1, { "loser.md": counts(1) });
  const marks = basicFiles(1);
  const space = workspace({
    pages: { ...basicPages(), "loser.md": "[one](target.md)\n" },
    population: populationSource({
      fileOccurrences: files,
      fileOccurrencesHighWaterMarks: marks,
      internalOccurrences: 2,
    }),
  });
  try {
    const result = space.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /loser\.md/);
  } finally {
    space.cleanup();
  }
});

test("defect 6: a recorded file whose links fall to zero refuses without authorization", () => {
  const files = basicFiles(1, { "loser.md": counts(1) });
  const space = workspace({
    pages: { ...basicPages(), "loser.md": "[one](target.md)\n" },
    population: populationSource({ fileOccurrences: files, internalOccurrences: 2 }),
  });
  try {
    writeFileSync(path.join(space.tree, "loser.md"), "no links\n");
    writeFileSync(path.join(space.tree, "README.md"), `${basicPages()["README.md"]}[two](target.md)\n`);
    const result = space.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /loser\.md/);
  } finally {
    space.cleanup();
  }
});

test("defect 7: omitted key plus compensated partial shrink refuses and names the file", () => {
  const files = basicFiles(1, { "loser.md": counts(2) });
  const marks = basicFiles(1);
  const space = workspace({
    pages: { ...basicPages(), "loser.md": "[one](target.md)\n[two](target.md)\n" },
    population: populationSource({
      fileOccurrences: files,
      fileOccurrencesHighWaterMarks: marks,
      internalOccurrences: 3,
    }),
  });
  try {
    writeFileSync(path.join(space.tree, "loser.md"), "[one](target.md)\n");
    writeFileSync(path.join(space.tree, "README.md"), `${basicPages()["README.md"]}[two](target.md)\n`);
    const result = space.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /loser\.md/);
  } finally {
    space.cleanup();
  }
});

test("content rule: the per-file record is complete", () => {
  const files = basicFiles(1, { "loser.md": counts(1) });
  const space = workspace({
    pages: { ...basicPages(), "loser.md": "[one](target.md)\n" },
    population: populationSource({
      fileOccurrences: files,
      fileOccurrencesHighWaterMarks: basicFiles(1),
      internalOccurrences: 2,
    }),
  });
  try {
    const result = space.run();
    assert.equal(result.status, 1, output(result));
  } finally {
    space.cleanup();
  }
});

test("content rule: the per-file record has no stranger keys", () => {
  const files = basicFiles();
  const marks = basicFiles(1, { "stranger.md": counts(0) });
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, fileOccurrencesHighWaterMarks: marks, internalOccurrences: 1 }),
  });
  try {
    const result = space.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /stranger\.md/);
  } finally {
    space.cleanup();
  }
});

test("content rule: per-file counts are non-negative integers", () => {
  const files = basicFiles();
  const base = populationSource({ fileOccurrences: files, internalOccurrences: 1 });
  for (const value of ["-1", "1.5", '"1"']) {
    const poisoned = base.replace('"internalOccurrences": 1', `"internalOccurrences": ${value}`);
    const space = workspace({ pages: basicPages(), population: poisoned });
    try {
      const result = space.run();
      assert.equal(result.status, 1, `${value}: ${output(result)}`);
    } finally {
      space.cleanup();
    }
  }
});

test("content rule: the per-file record has no duplicate keys", () => {
  const files = basicFiles();
  const base = populationSource({ fileOccurrences: files, internalOccurrences: 1 });
  const marker = "  fileOccurrencesHighWaterMarks:   {\n";
  const markerIndex = base.indexOf(marker);
  assert.notEqual(markerIndex, -1, "test fixture must find the high-water record object");
  const insertAt = markerIndex + marker.length;
  const duplicate = `${base.slice(0, insertAt)}    "README.md": { "internalOccurrences": 0, "externalOccurrences": 0 },\n${base.slice(insertAt)}`;
  const space = workspace({ pages: basicPages(), population: duplicate });
  try {
    const result = space.run();
    assert.equal(result.status, 1, output(result));
    assert.match(result.stderr, /duplicate key.*README\.md/);
  } finally {
    space.cleanup();
  }
});

test("pass path: no-op exits zero without rewriting the record", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  try {
    const before = sha256(space.record);
    const result = space.run();
    assert.equal(result.status, 0, output(result));
    assert.equal(sha256(space.record), before);
  } finally {
    space.cleanup();
  }
});

test("pass path: one added link exits zero", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  try {
    writeFileSync(path.join(space.tree, "README.md"), `${basicPages()["README.md"]}[two](target.md)\n`);
    const result = space.run();
    assert.equal(result.status, 0, output(result));
  } finally {
    space.cleanup();
  }
});

test("pass path: a new page with links exits zero", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  try {
    writeFileSync(path.join(space.tree, "new.md"), "[one](target.md)\n[two](target.md)\n");
    const result = space.run();
    assert.equal(result.status, 0, output(result));
  } finally {
    space.cleanup();
  }
});

test("pass path: a new page without links exits zero", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  try {
    writeFileSync(path.join(space.tree, "new.md"), "no links\n");
    const result = space.run();
    assert.equal(result.status, 0, output(result));
  } finally {
    space.cleanup();
  }
});

test("pass path: two writes in a row are idempotent", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  try {
    const first = space.run();
    const afterFirst = sha256(space.record);
    const second = space.run();
    assert.equal(first.status, 0, output(first));
    assert.equal(second.status, 0, output(second));
    assert.equal(sha256(space.record), afterFirst);
  } finally {
    space.cleanup();
  }
});

test("pass path: a named shrink retires a deleted page key", () => {
  const files = basicFiles(1, { "retired.md": counts(1) });
  const space = workspace({
    pages: { ...basicPages(), "retired.md": "[one](target.md)\n" },
    population: populationSource({ fileOccurrences: files, internalOccurrences: 2 }),
  });
  try {
    rmSync(path.join(space.tree, "retired.md"));
    const result = space.run("--allow-shrink", "retired.md");
    assert.equal(result.status, 0, output(result));
    assert.doesNotMatch(readFileSync(space.record, "utf8"), /retired\.md/);
  } finally {
    space.cleanup();
  }
});

test("a bare or unused allow-shrink authorization refuses", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  try {
    const bare = space.run("--allow-shrink");
    const unused = space.run("--allow-shrink", "README.md");
    assert.equal(bare.status, 2, output(bare));
    assert.equal(unused.status, 1, output(unused));
    assert.match(output(unused), /did not shrink|unused/i);
  } finally {
    space.cleanup();
  }
});

test("the fixture cleanup removes every scratch mutation", () => {
  const files = basicFiles();
  const space = workspace({
    pages: basicPages(),
    population: populationSource({ fileOccurrences: files, internalOccurrences: 1 }),
  });
  const scratch = space.space;
  space.cleanup();
  assert.equal(existsSync(scratch), false);
});
