/- SPDX-License-Identifier: Apache-2.0 -/

import Lean.Data.Json
import Seal.Policy
import Seal.PolicyBundle
import Seal.JsonUtil

/-!
# Pre-codec policy parsers — the Layer-1 equivalence SPEC

VERBATIM copies of `parsePolicyJson` / `parsePolicyBundle` and their helpers
as they stood before the schema-carrying codec refactor (mcp-seal-dev `main`,
2bc303e). This module is proof-only: nothing here is exported to the host —
it exists so `Seal/PolicyEquiv.lean` can state and prove that the codec
parsers accept EXACTLY the same wire language (same verdict, same value, same
error text).

Two constants are shared with the live parser rather than copied:

* `Seal.parseMatch` — `partial`, hence kernel-opaque; the codec reuses the
  constant itself (`matchCodec`), so match acceptance is identical by
  construction and a copy could not be related to it by any theorem anyway;
* `Seal.parseTargetPart` — shared for the same by-construction identity
  (total, but control-flow-shaped; the codec reuses it verbatim).

Do NOT edit this file except in lockstep with a DELIBERATE acceptance-set
change (a Layer-2 format commit), in which case the equivalence theorems must
be re-stated against the new spec, not silently weakened.

LAYER-2 CHANGES APPLIED (each one IS the documented acceptance-set delta —
review this file's history to read the delta directly):

* V2.1 principals (mcp-seal-dev 8761fae re-expressed): `bundleTopLevelKeys`
  gains `"principals"`, and `parsePrincipalsSection` / `parsePrincipalKey`
  (inline `mapM` lambda hoisted, body identical) are copied VERBATIM from
  the 8761fae parser. Everything else is byte-identical to the pre-codec
  spec, so the non-principals acceptance set is unchanged.

* Stage A guard-target restriction (2026-07-21): `parseToolRule` gains the
  guarded-mode target check — a rule with `mode: guard`/`guarded` whose
  target is not exactly `[{"full_arguments": true}]` is a hard parse error
  (`Seal.guardTargetErrorText`). The check is the shared constant
  `Seal.guardCheck` (the `parseMatch` sharing discipline), inserted at
  the SAME position (after target parse, before emit) as the codec's
  `ObjSpec.check`. This is the documented acceptance-set delta: every
  previously-accepted guarded rule with a `literal`/`arg`/empty target is
  now rejected; nothing else changes.
-/

namespace Seal.PolicyLegacy

open Lean
open Seal.JsonUtil
open Seal (MatchSpec TargetPart ToolMode ToolRule Policy maxApprovalTtlSeconds
           parseMatch parseTargetPart TemporalRule TemporalSection
           ConsensusSection ConvergentTool ConvergenceSection
           CalibrationSection LinearGrantTool LinearSection BudgetRule
           BudgetSection PrincipalKeyEntry PrincipalsSection PolicyBundle)

def parseToolRule (json : Json) : Except String ToolRule := do
  let name ← getObjString json "name"
  let modeText ← getObjString json "mode"
  let mode ← match modeText with
    | "allow" => pure ToolMode.allow
    | "guard" => pure ToolMode.guarded
    | "guarded" => pure ToolMode.guarded
    | "deny" => pure ToolMode.deny
    | other => throw s!"unsupported tool mode: {other}"
  let matcher ←
    match ← getObjValOpt json "match" with
    | some m => parseMatch m
    | none => pure .always
  let target ←
    match ← getObjValOpt json "target" with
    | some (.arr parts) => parts.toList.mapM parseTargetPart
    | some _ => throw "target must be an array"
    | none => pure []
  let _ ← Seal.guardCheck mode target
  pure { name, mode, matcher, target }

def parsePolicyJson (json : Json) : Except String Policy := do
  let approval ← json.getObjVal? "approval"
  let approvalTtlSeconds ← getObjNatD approval "ttl_seconds" 120
  let approvalTtlMs := (min approvalTtlSeconds maxApprovalTtlSeconds) * 1000
  let approvalFile := System.FilePath.mk (← getObjString approval "control_file")
  let serverIdentity ← match ← getObjValOpt json "server" with
    | some value => value.getStr?
    | none => pure ""
  let toolsJson ← (← json.getObjVal? "tools").getArr?
  let tools ← toolsJson.toList.mapM parseToolRule
  pure { approvalTtlMs, approvalFile, serverIdentity, tools }

def parseStringList (json : Json) : Except String (List String) := do
  let arr ← json.getArr?
  arr.toList.mapM (fun j => j.getStr?)

def parseEnabled (json : Json) (default : Bool) : Except String Bool := do
  match ← getObjValOpt json "enabled" with
  | some v => v.getBool?
  | none => pure default

def parseTemporalRule (json : Json) : Except String TemporalRule := do
  expectObjKeys json ["name", "type", "trigger", "forbidden"] "temporal policy"
  let name ← getObjString json "name"
  let kind ← getObjString json "type"
  if kind != "no_after" then
    throw s!"unsupported temporal policy type: {kind}"
  let trigger ← parseStringList (← json.getObjVal? "trigger")
  let forbidden ← parseStringList (← json.getObjVal? "forbidden")
  pure { name, trigger, forbidden }

def parseTemporalSection (json : Json) : Except String TemporalSection := do
  expectObjKeys json ["enabled", "policies"] "temporal section"
  let enabled ← parseEnabled json true
  let policiesJson ← (← json.getObjVal? "policies").getArr?
  let policies ← policiesJson.toList.mapM parseTemporalRule
  pure { enabled, policies }

def parseConsensusSection (json : Json) : Except String ConsensusSection := do
  expectObjKeys json ["enabled", "roster", "votes_file", "high_stakes"]
    "consensus section"
  let enabled ← parseEnabled json true
  let rosterJson ← (← json.getObjVal? "roster").getArr?
  let roster ← rosterJson.toList.mapM (fun j => j.getNat?)
  let votesFile ← getObjString json "votes_file"
  let highStakes ← parseStringList (← json.getObjVal? "high_stakes")
  pure { enabled, roster, votesFile, highStakes }

/-- The pre-codec convergence-tool entry parser. In the pre-codec source this
    was an inline lambda under `mapM`; it is hoisted to a named def with an
    IDENTICAL body so the equivalence lemma can name it. Behavior unchanged. -/
def parseConvergentTool : Json → Except String ConvergentTool := fun j => do
  expectObjKeys j ["tool", "op_arg"] "convergence tool"
  let tool ← getObjString j "tool"
  let opArg ← getObjString j "op_arg"
  pure { tool, opArg := splitPath opArg : ConvergentTool }

def parseConvergenceSection (json : Json) : Except String ConvergenceSection := do
  expectObjKeys json ["enabled", "tools"] "convergence section"
  let enabled ← parseEnabled json true
  let toolsJson ← (← json.getObjVal? "tools").getArr?
  let tools ← toolsJson.toList.mapM parseConvergentTool
  pure { enabled, tools }

def parseCalibrationSection (json : Json) : Except String CalibrationSection := do
  expectObjKeys json
    ["enabled", "delta_num", "delta_den", "min_samples", "records_file",
     "gated_tools"] "calibration section"
  let enabled ← parseEnabled json false
  let deltaNum ← (← json.getObjVal? "delta_num").getNat?
  let deltaDen ← (← json.getObjVal? "delta_den").getNat?
  if deltaNum == 0 || deltaDen ≤ deltaNum then
    throw "calibration delta must satisfy 0 < delta < 1"
  let minSamples ← (← json.getObjVal? "min_samples").getNat?
  let recordsFile ← getObjString json "records_file"
  let gatedTools ← parseStringList (← json.getObjVal? "gated_tools")
  pure { enabled, deltaNum, deltaDen, minSamples, recordsFile, gatedTools }

/-- The pre-codec linear-tool entry parser; hoisted from the inline `mapM`
    lambda with an IDENTICAL body (see `parseConvergentTool`). -/
def parseLinearTool : Json → Except String LinearGrantTool := fun j => do
  expectObjKeys j ["tool", "cap_arg"] "linear tool"
  let tool ← getObjString j "tool"
  let capArg ← getObjString j "cap_arg"
  pure { tool, capArg := splitPath capArg : LinearGrantTool }

def parseLinearSection (json : Json) : Except String LinearSection := do
  expectObjKeys json ["enabled", "grants_file", "tools"] "linear section"
  let enabled ← parseEnabled json true
  let grantsFile ← getObjString json "grants_file"
  let toolsJson ← (← json.getObjVal? "tools").getArr?
  let tools ← toolsJson.toList.mapM parseLinearTool
  pure { enabled, grantsFile, tools }

def parseBudgetRule (j : Json) : Except String BudgetRule := do
  expectObjKeys j ["name", "cap", "tools", "cost_arg"] "budget spec"
  let name ← getObjString j "name"
  let cap ← (← j.getObjVal? "cap").getNat?
  let tools ← parseStringList (← j.getObjVal? "tools")
  let costArg ← match ← getObjValOpt j "cost_arg" with
    | some v => pure (some (splitPath (← v.getStr?)))
    | none => pure none
  pure { name, cap, tools, costArg }

def parseBudgetSection (json : Json) : Except String BudgetSection := do
  expectObjKeys json ["enabled", "budgets"] "budget section"
  let enabled ← parseEnabled json true
  let budgetsJson ← (← json.getObjVal? "budgets").getArr?
  let budgets ← budgetsJson.toList.mapM parseBudgetRule
  pure { enabled, budgets }

private def isHexChar (c : Char) : Bool :=
  c.isDigit || ('a' ≤ c && c ≤ 'f') || ('A' ≤ c && c ≤ 'F')

/-- The 8761fae principal-key entry parser; hoisted from the inline `mapM`
    lambda with an IDENTICAL body (see `parseConvergentTool`). -/
def parsePrincipalKey : Json → Except String PrincipalKeyEntry := fun j => do
  expectObjKeys j ["id", "pubkey"] "principal key"
  let id ← getObjString j "id"
  let pubkey ← getObjString j "pubkey"
  if id.isEmpty then
    throw "principal id must be non-empty"
  if pubkey.length != 64 || !(pubkey.toList.all isHexChar) then
    throw s!"principal pubkey must be 64 hex chars: {id}"
  pure { id, pubkey : PrincipalKeyEntry }

def parsePrincipalsSection (json : Json) : Except String PrincipalsSection := do
  expectObjKeys json ["enabled", "keys", "budgets"] "principals section"
  let enabled ← parseEnabled json true
  let keysJson ← (← json.getObjVal? "keys").getArr?
  let keys ← keysJson.toList.mapM parsePrincipalKey
  let budgetsJson ← (← json.getObjVal? "budgets").getArr?
  let budgets ← budgetsJson.toList.mapM parseBudgetRule
  pure { enabled, keys, budgets }

def parseOptSection {α : Type} (json : Json) (key : String)
    (parse : Json → Except String α) : Except String (Option α) := do
  match ← getObjValOpt json key with
  | none => pure none
  | some section_ => pure (some (← parse section_))

def bundleTopLevelKeys : List String :=
  ["epoch", "server", "safety", "temporal", "consensus", "convergence",
   "calibration", "linear", "budget", "principals"]

def safetyShallowKeys : List String := ["approval", "tools", "server"]

def approvalKeys : List String := ["control_file", "ttl_seconds", "replay_store"]

def parsePolicyBundle (json : Json) : Except String PolicyBundle := do
  expectObjKeys json bundleTopLevelKeys "policy bundle"
  let epoch ← (← json.getObjVal? "epoch").getNat?
  if epoch == 0 then
    throw "config epoch must be ≥ 1"
  let safetyJson ← json.getObjVal? "safety"
  expectObjKeys safetyJson safetyShallowKeys "safety section"
  expectObjKeys (← safetyJson.getObjVal? "approval") approvalKeys "safety approval"
  let outerServer ← match ← getObjValOpt json "server" with
    | some value => pure (some (← value.getStr?))
    | none => pure none
  let innerServer ← match ← getObjValOpt safetyJson "server" with
    | some value => pure (some (← value.getStr?))
    | none => pure none
  if outerServer.isSome && innerServer.isSome && outerServer != innerServer then
    throw "server identity conflicts between trusted config and safety policy"
  let safetyJson := match outerServer, innerServer with
    | some server, none => safetyJson.setObjVal! "server" (.str server)
    | _, _ => safetyJson
  let safety ← parsePolicyJson safetyJson
  let temporal ← parseOptSection json "temporal" parseTemporalSection
  let consensus ← parseOptSection json "consensus" parseConsensusSection
  let convergence ← parseOptSection json "convergence" parseConvergenceSection
  let calibration ← parseOptSection json "calibration" parseCalibrationSection
  let linear ← parseOptSection json "linear" parseLinearSection
  let budget ← parseOptSection json "budget" parseBudgetSection
  let principals ← parseOptSection json "principals" parsePrincipalsSection
  pure { epoch, safety, temporal, consensus, convergence, calibration, linear,
         budget, principals }

end Seal.PolicyLegacy
