#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
//
// Seal bootstrap installer.
//
// This file is a THIN, VERIFIED FRONT DOOR to the real installer
// (scripts/install.cjs, which is the head of every published release
// artifact -- see scripts/build-dist.cjs). It does not reimplement, weaken,
// or bypass any check install.cjs already performs. It:
//
//   1. detects the running platform/architecture and Node version,
//   2. picks the matching release artifact from an embedded, release-
//      specific map of {platform, name, sha256, bytes} generated by
//      scripts/generate-bootstrap.mjs from the SAME validated release
//      manifest scripts/install.cjs and scripts/build-dist.cjs already
//      trust (never hand-typed),
//   3. downloads that one artifact to a private temporary directory,
//   4. independently verifies its COMPLETE byte length and SHA-256 digest
//      against the embedded map before touching anything else, and
//   5. only then executes the verified artifact -- which physically
//      contains scripts/install.cjs's own source -- with the required
//      --sha256/--bytes/--prefix pins, so install.cjs's own digest check,
//      platform gate, and ownership/reinstall logic run completely
//      unchanged and unweakened.
//
// HONESTY LIMIT (read this before trusting this file): this binds the
// downloaded bytes to the release information you accepted -- the
// artifact's digest and length, embedded below, checked against what
// actually arrived over the network. It does NOT establish that the
// publisher, the hosting account, or the release itself is honest. A
// compromised release pipeline or hosting account could serve a
// consistently-malicious artifact whose bytes still match every digest
// recorded here, because those digests were produced by the same
// compromise. Nothing in this file, or in install.cjs, closes that gap.
//
// SELF-VERIFICATION: this file's OWN bytes must be checked with an
// already-installed OS tool (shasum -a 256 / sha256sum) against the hash
// published alongside it, BEFORE you run it. That check cannot happen from
// inside this file -- a tampered copy would simply skip it -- so it is not
// implemented here. See the published install instructions for the exact
// command. scripts/generate-bootstrap.mjs computes that hash from this
// file's frozen bytes and writes it to a sidecar next to the artifact; it
// is never embedded in the bytes it describes (see that script for why).
"use strict";

const crypto = require("node:crypto");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync, execFileSync } = require("node:child_process");

// Replaced verbatim, exactly once, by scripts/generate-bootstrap.mjs with a
// JSON object: { schema, repository, tag, commitSha, minimumNodeMajor,
// artifacts: [{ platform, name, sha256, bytes }, ...] }. This object is
// frozen release data; it must never contain a hash of this file itself
// (see the header comment above and scripts/generate-bootstrap.mjs).
const RELEASE = "__SEAL_BOOTSTRAP_RELEASE_FACTS_JSON__";

function refuseWith(cleanupTmp) {
  return (code, reason, remedy) => {
    cleanupTmp();
    process.stderr.write(`REFUSE ${code}: ${reason}\n`);
    if (remedy) process.stderr.write(`${remedy}\n`);
    process.exit(1);
  };
}

// Same convention scripts/install.cjs uses for the same reason: this file is
// shipped as `node - "$0" "$@"` inside a shell stub (see the header that
// scripts/generate-bootstrap.mjs wraps around it), which places the real
// script path at argv[2] instead of argv[1] when Node reads from stdin.
function bootstrapFlags(argv) {
  return argv[1] === "-" ? argv.slice(3) : argv.slice(2);
}

function parseArgs(argv, refuse) {
  const out = {};
  const flags = bootstrapFlags(argv);
  for (let i = 0; i < flags.length; i += 1) {
    if (flags[i] === "--prefix") {
      const value = flags[i + 1];
      if (value === undefined) refuse("flag_missing", "--prefix needs a value.", "re-run with --prefix <path>, or omit --prefix to install under ~/.local.");
      out.prefix = value;
      i += 1;
      continue;
    }
    refuse("unknown_flag", `unknown bootstrap flag: ${flags[i]}`, "supported flags: --prefix <path>.");
  }
  return out;
}

// Host identity uses the same env-var test seam scripts/install.cjs already
// exposes (SEAL_SPINE_PLATFORM / SEAL_SPINE_ARCH), so both files pick the
// same artifact for the same host by construction, and both can be exercised
// under test without real cross-platform hardware.
function hostPlatform() {
  const platform = process.env.SEAL_SPINE_PLATFORM || process.platform;
  const arch = process.env.SEAL_SPINE_ARCH || process.arch;
  return { platform, arch, id: `${platform}-${arch}` };
}

// DELIBERATE DESIGN CHOICE, not a bug: process.arch reports the architecture
// of the running Node BINARY, and that is exactly what determines which
// artifact's native pieces will load -- it is honest for that purpose even
// when Node itself is an x64 build running translated under Rosetta on
// Apple Silicon. This probe is informational ONLY. It must never override
// artifact selection: doing so would hand an arm64-native Node process's
// artifact to an x64-translated one (or vice versa), which is the actual
// dishonesty risk here. SEAL_BOOTSTRAP_FORCE_ROSETTA overrides the probe for
// tests that cannot depend on real Apple Silicon hardware.
function rosettaTranslated() {
  const forced = process.env.SEAL_BOOTSTRAP_FORCE_ROSETTA;
  if (forced === "1") return true;
  if (forced === "0") return false;
  if (process.platform !== "darwin") return false;
  try {
    const out = execFileSync("sysctl", ["-n", "sysctl.proc_translated"], { encoding: "utf8" }).trim();
    return out === "1";
  } catch {
    // Absent on Intel Macs and on macOS versions without Rosetta, and
    // harmless to under-report elsewhere: this is informational only.
    return false;
  }
}

async function downloadAndVerify(url, expectedBytes, expectedSha256, destPath, { timeoutMs = 30000 } = {}) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(new Error(`no response within ${timeoutMs}ms`)), timeoutMs);
  let response;
  try {
    response = await fetch(url, { redirect: "follow", signal: controller.signal });
  } catch (error) {
    return { ok: false, code: "download_failed", reason: `could not reach ${url}: ${error.message}` };
  } finally {
    clearTimeout(timer);
  }
  if (!response.ok || !response.body) {
    return { ok: false, code: "download_failed", reason: `download of ${url} failed: HTTP ${response.status}` };
  }
  const hash = crypto.createHash("sha256");
  let received = 0;
  const file = fs.createWriteStream(destPath, { mode: 0o600, flags: "wx" });
  try {
    for await (const chunk of response.body) {
      received += chunk.length;
      // Enforced DURING the stream, not only at the end: an artifact whose
      // published length we already know must never be allowed to grow the
      // download past that length first. Bound the work an untrusted or
      // compromised host can make this machine do before any check runs.
      if (received > expectedBytes) {
        file.destroy();
        try { fs.unlinkSync(destPath); } catch { /* best-effort; the refusal is what matters */ }
        return { ok: false, code: "artifact_oversized", reason: `download of ${url} exceeded the published length of ${expectedBytes} bytes` };
      }
      hash.update(chunk);
      if (!file.write(chunk)) await new Promise((resolve) => file.once("drain", resolve));
    }
  } catch (error) {
    file.destroy();
    try { fs.unlinkSync(destPath); } catch { /* best-effort; the refusal is what matters */ }
    return { ok: false, code: "download_failed", reason: `download of ${url} was interrupted: ${error.message}` };
  }
  // Wait for the underlying file descriptor to actually CLOSE, not just for
  // writes to finish. `end(callback)` fires on Node's 'finish' event, which
  // can land before the fd is closed at the OS level; under real scheduling
  // load, execve()-ing this file a moment too early hits Linux's ETXTBSY
  // ("text file busy") because a writable fd is still open on it. This is
  // the whole reason downloadAndVerify returns before anyone chmods or
  // executes destPath.
  await new Promise((resolve, reject) => {
    file.once("error", reject);
    file.end(() => file.once("close", resolve));
  });
  if (received !== expectedBytes) {
    return { ok: false, code: "artifact_truncated", reason: `downloaded ${received} bytes from ${url}; the release names ${expectedBytes}` };
  }
  const digest = hash.digest("hex");
  if (digest !== expectedSha256) {
    return { ok: false, code: "artifact_digest_mismatch", reason: `downloaded bytes from ${url} hash to ${digest}; the release names ${expectedSha256}` };
  }
  return { ok: true, digest, bytes: received };
}

async function main() {
  let tmpDir = null;
  const cleanupTmp = () => {
    if (!tmpDir) return;
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* best-effort; nothing else was created */ }
    tmpDir = null;
  };
  const refuse = refuseWith(cleanupTmp);

  if (
    !RELEASE || typeof RELEASE !== "object" || typeof RELEASE.tag !== "string" ||
    !/^v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$/.test(RELEASE.tag) ||
    typeof RELEASE.repository !== "string" || !/^[^/\s]+\/[^/\s]+$/.test(RELEASE.repository) ||
    !Array.isArray(RELEASE.artifacts) || RELEASE.artifacts.length === 0 ||
    !Number.isInteger(RELEASE.minimumNodeMajor)
  ) {
    refuse(
      "bootstrap_malformed",
      "this bootstrap script's embedded release data is missing or invalid.",
      "download a fresh copy from the release page; do not hand-edit this file.",
    );
  }

  const args = parseArgs(process.argv, refuse);

  const nodeMajor = Number.parseInt(process.versions.node, 10);
  if (!Number.isFinite(nodeMajor) || nodeMajor < RELEASE.minimumNodeMajor) {
    refuse(
      "node_too_old",
      `this release requires Node >= ${RELEASE.minimumNodeMajor}; this process is running Node ${process.versions.node}.`,
      `install a newer Node (for example "nvm install ${RELEASE.minimumNodeMajor}", or your OS package manager), then re-run this script.`,
    );
  }

  const plat = hostPlatform();
  if (plat.platform === "darwin" && rosettaTranslated()) {
    process.stderr.write(
      `NOTE: this Node process is running translated under Rosetta (reports as ${plat.id}). ` +
      "That is what determines which release asset will load correctly, so the matching " +
      `${plat.id} asset will be installed. A native darwin-arm64 Node would run faster but is not required.\n`,
    );
  }
  const artifact = RELEASE.artifacts.find((entry) => entry.platform === plat.id);
  if (!artifact) {
    const supported = RELEASE.artifacts.map((entry) => entry.platform).sort().join(", ");
    refuse(
      "unsupported_platform",
      `${RELEASE.tag} publishes no release asset for ${plat.id}.`,
      `Seal ${RELEASE.tag} supports: ${supported}. No files were changed.`,
    );
  }
  // Belt-and-braces, same reasoning as install.cjs's own payload-path guard
  // (scripts/install.cjs checks `file.path.split("/").includes("..")`): the
  // embedded map is generator-produced and trusted, but a name is about to
  // become both a URL path segment and a filesystem path component, so it is
  // cheap and worthwhile to refuse anything that is not a plain filename
  // before either use, rather than assume the embed can never be malformed.
  if (!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(artifact.name)) {
    refuse(
      "bootstrap_malformed",
      `this bootstrap's embedded artifact name for ${plat.id} is not a plain filename: ${JSON.stringify(artifact.name)}.`,
      "download a fresh copy from the release page; do not hand-edit this file.",
    );
  }

  const prefix = path.resolve(args.prefix || path.join(os.homedir(), ".local"));

  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "seal-bootstrap-"));
  const artifactPath = path.join(tmpDir, artifact.name);
  const baseUrl = process.env.SEAL_BOOTSTRAP_DOWNLOAD_BASE_URL // test-only seam; never advertised to users
    || `https://github.com/${RELEASE.repository}/releases/download/${RELEASE.tag}`;
  const url = `${baseUrl}/${artifact.name}`;

  const outcome = await downloadAndVerify(url, artifact.bytes, artifact.sha256, artifactPath);
  if (!outcome.ok) {
    refuse(
      outcome.code,
      outcome.reason,
      "check your network connection and try again. If the problem persists, compare the release page's " +
      `SHA256SUMS for ${artifact.name} with the values embedded in this bootstrap.`,
    );
  }

  fs.chmodSync(artifactPath, 0o755);
  process.stdout.write(`Verified ${artifact.name}: sha256 ${artifact.sha256}, ${artifact.bytes} bytes.\n`);
  process.stdout.write(`Handing off to the installer with prefix ${prefix}...\n`);

  // The verified artifact IS scripts/install.cjs (its source is the head of
  // every built artifact -- see scripts/build-dist.cjs). This call does not
  // duplicate or reinterpret install.cjs's checks; it supplies exactly the
  // pins install.cjs already requires and lets it run unmodified.
  const result = spawnSync(artifactPath, [
    "--sha256", artifact.sha256,
    "--bytes", String(artifact.bytes),
    "--prefix", prefix,
  ], { stdio: "inherit" });

  cleanupTmp();

  if (result.error) {
    process.stderr.write(`REFUSE installer_launch_failed: could not run the downloaded installer: ${result.error.message}\n`);
    process.exit(1);
  }
  process.exit(result.status ?? 1);
}

main();
